inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

Lint/MissingSuper:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/features/**/*'

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

Capybara/VisibilityMatcher:
  Enabled: false

RSpec/ContextWording:
  Exclude:
    - 'spec/decorators/**/*'
