name: liburrun
services:
  base:
    image: liburrun:latest
  common_frontend:
    extends:
      service: base
    volumes:
      - .:/liburrun_app
      - node_modules:/liburrun_app/node_modules
  common_backend:
    extends:
      service: base
    volumes:
      - .:/liburrun_app
  db:
    image: postgres:14.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 60s
      timeout: 10s
      retries: 3
  web:
    extends:
      service: common_backend
    build: .
    command: bin/rails server -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/liburrun_app/node_modules
    depends_on:
      - db
      - redis
  worker:
    extends:
      service: common_backend
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - web
  css:
    extends:
      service: common_frontend
    command: yarn build:css --watch
    stdin_open: true
    depends_on:
      - web
  js:
    extends:
      service: common_frontend
    command: yarn build --watch
    stdin_open: true
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data:
  node_modules:
